# Generated by Django 5.0 on 2025-09-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_reviewvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewVote',
        ),
    ]
