# Generated by Django 5.2.7 on 2025-12-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_purchaseevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R')], default='PG-13', max_length=5),
        ),
    ]
